const $=s=>document.querySelector(s);const app=$('#app');const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(u,o){const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Помилка');return d}function toast(x){const t=$('#toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}function page(p,id=''){location.href='?page='+encodeURIComponent(p)+(id?'&id='+encodeURIComponent(id):'')}
function card(v){return `<article class="card" onclick="page('video','${v.id}')"><img class="thumb" src="${esc(v.thumbnail_url||'')}" onerror="this.style.visibility='hidden'"><div class="meta"><img class="avatar" src="${esc(v.channel_avatar||'')}"><div><div class="title">${esc(v.title)}</div><div class="muted">${esc(v.channel_name)} · ${Number(v.views||0).toLocaleString()} переглядів</div></div></div></article>`}
async function home(search=''){const d=await api(search?'/api/search?q='+encodeURIComponent(search):'/api/home');app.innerHTML=`<h1 class="section-title">${search?'Результати пошуку':'Рекомендовані відео'}</h1><div class="grid">${d.videos.map(card).join('')||'<div class="empty">Відео ще немає.</div>'}</div>`}
async function video(id){const d=await api('/api/video/'+id),v=d.video;app.innerHTML=`<div class="video-page"><video class="video-player" controls playsinline poster="${esc(v.thumbnail_url)}" src="${esc(v.video_url)}"></video><h1>${esc(v.title)}</h1><div class="muted">${esc(v.channel_name)} · ${Number(v.views).toLocaleString()} переглядів</div><div class="actions"><button class="pill" id="like">👍 ${v.likes}</button><button class="pill" id="sub">${v.subscribed?'✓ Підписано':'＋ Підписатися'} · ${v.subscribers}</button><button class="pill" onclick="page('channel','${v.channel_id}')">Канал</button></div><p>${esc(v.description)}</p><div class="comments"><h2>Коментарі (${v.comments})</h2><div class="row"><input class="input" id="commentText" placeholder="Написати коментар…"><button class="green" id="commentBtn">Надіслати</button></div>${(v.commentsList||[]).map(c=>`<div class="comment">${esc(c.text)} <small class="muted">${new Date(c.created_at).toLocaleString()}</small>${'<button class="pill" onclick="delComment(\''+c.id+'\',\''+id+'\')">Видалити</button>'}</div>`).join('')}</div></div>`;$('#like').onclick=async()=>{const x=await api('/api/like/'+id,{method:'POST'});$('#like').textContent='👍 '+x.likes};$('#sub').onclick=async()=>{const x=await api('/api/subscribe/'+v.channel_id,{method:'POST'});$('#sub').textContent=(x.subscribed?'✓ Підписано':'＋ Підписатися')+' · '+x.subscribers};$('#commentBtn').onclick=async()=>{await api('/api/comment/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('#commentText').value})});video(id)}}
async function delComment(cid,vid){await api('/api/comment/'+cid,{method:'DELETE'});video(vid)}
async function profile(){const d=await api('/api/me');app.innerHTML=`<div class="panel"><h1>Профіль</h1><label>Ім'я<input class="input" id="username" value="${esc(d.profile?.username||'')}"></label><label>Опис<textarea id="bio">${esc(d.profile?.bio||'')}</textarea></label><label>Аватар<input class="input" type="file" id="avatar" accept="image/*"></label><button class="green" onclick="saveProfile()">Зберегти</button><hr><button class="pill" onclick="page('channel')">Мій канал</button></div>`}
async function saveProfile(){const f=new FormData();f.append('username',$('#username').value);f.append('bio',$('#bio').value);if($('#avatar').files[0])f.append('avatar',$('#avatar').files[0]);await api('/api/profile',{method:'POST',body:f});toast('Профіль збережено')}
async function channel(id){let d;if(id)d=await api('/api/channel/'+id);else{const m=await api('/api/me');if(!m.channel){createChannel();return}d=await api('/api/channel/'+m.channel.id)}const c=d.channel;app.innerHTML=`<div><img class="banner" src="${esc(c.banner_url||'')}" onerror="this.style.visibility='hidden'"><div class="channel-head"><img class="channel-avatar" src="${esc(c.avatar_url||'')}"><div><h1>${esc(c.name)}</h1><div class="muted">${d.subscribers} підписників</div><p>${esc(c.description)}</p></div><div style="margin-left:auto">${d.is_owner?'<button class="pill" onclick="editChannel()">Редагувати</button>':''}<button class="green" onclick="subChannel(\''+c.id+'\')">${d.subscribed?'✓ Підписано':'Підписатися'}</button></div></div><h2>Відео</h2><div class="grid">${d.videos.map(v=>card(v)).join('')||'<div class="empty">У каналу ще немає відео.</div>'}</div></div>`;window.currentChannel=c;window.currentChannelOwner=d.is_owner}
async function subChannel(id){const x=await api('/api/subscribe/'+id,{method:'POST'});toast(x.subscribed?'Підписка оформлена':'Підписку скасовано');channel(id)}
function createChannel(){app.innerHTML=`<div class="panel"><h1>Створити канал</h1><input class="input" id="cname" placeholder="Назва каналу"><textarea id="cdesc" placeholder="Опис"></textarea><label>Аватар <input class="input" id="cavatar" type="file" accept="image/*"></label><label>Банер <input class="input" id="cbanner" type="file" accept="image/*"></label><button class="green" onclick="saveChannel(true)">Створити канал</button></div>`}
function editChannel(){const c=window.currentChannel;app.innerHTML=`<div class="panel"><h1>Редагувати канал</h1><input class="input" id="cname" value="${esc(c.name)}"><textarea id="cdesc">${esc(c.description)}</textarea><label>Новий аватар <input class="input" id="cavatar" type="file" accept="image/*"></label><label>Новий банер <input class="input" id="cbanner" type="file" accept="image/*"></label><button class="green" onclick="saveChannel(false)">Зберегти</button><button class="pill" onclick="upload()">Завантажити відео</button></div>`}
async function saveChannel(create){const f=new FormData();f.append('name',$('#cname').value);f.append('description',$('#cdesc').value);if($('#cavatar').files[0])f.append('avatar',$('#cavatar').files[0]);if($('#cbanner').files[0])f.append('banner',$('#cbanner').files[0]);await api(create?'/api/channel':'/api/channel',{method:create?'POST':'PUT',body:f});toast(create?'Канал створено':'Канал оновлено');page('channel')}
function upload(){app.innerHTML=`<div class="panel"><h1>Завантажити відео</h1><input class="input" id="vtitle" placeholder="Назва відео"><textarea id="vdesc" placeholder="Опис"></textarea><label>Відео<input class="input" id="vfile" type="file" accept="video/mp4,video/webm,video/quicktime"></label><label>Прев'ю<input class="input" id="thumb" type="file" accept="image/*"></label><button class="green" onclick="sendVideo()">Опублікувати</button></div>`}
async function sendVideo(){const f=new FormData();f.append('title',$('#vtitle').value);f.append('description',$('#vdesc').value);if(!$('#vfile').files[0])return toast('Вибери відео');f.append('video',$('#vfile').files[0]);if($('#thumb').files[0])f.append('thumbnail',$('#thumb').files[0]);toast('Завантаження…');await api('/api/upload',{method:'POST',body:f});toast('Відео опубліковано');page('home')}
async function owner(){app.innerHTML=`<div class="panel"><h1>Панель власника</h1><input class="input" id="op" type="password" placeholder="Пароль власника"><button class="green" onclick="loginOwner()">Увійти</button><div id="ownerArea"></div></div>`;const x=await api('/api/owner/check');if(x.owner)ownerArea()}
async function loginOwner(){await api('/api/owner/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#op').value})});ownerArea()}
async function ownerArea(){const d=await api('/api/home');$('#ownerArea').innerHTML='<h2>Відео</h2>'+d.videos.map(v=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #252a26"><span style="flex:1">${esc(v.title)}</span><button class="pill" onclick="ownerDel('${v.id}')">Видалити</button></div>`).join('')}
async function ownerDel(id){await api('/api/owner/video/'+id,{method:'DELETE'});ownerArea()}
$('#menu').onclick=()=>{$('#side').classList.toggle('open')};$('#search').onsubmit=e=>{e.preventDefault();home($('#q').value)};
async function start(){try{const p=new URLSearchParams(location.search),x=p.get('page')||'home',id=p.get('id');if(x==='video')await video(id);else if(x==='profile')await profile();else if(x==='channel')await channel(id);else if(x==='upload')await upload();else if(x==='owner')await owner();else await home(x==='search'?p.get('q')||'':location.search.includes('q=')?p.get('q')||'':'')}catch(e){app.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}start();
