services:
  - type: web
    name: limetube
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_KEY
        sync: false

      - key: SUPABASE_SECRET_KEY
        sync: false

      - key: OWNER_PASSWORD
        sync: false

      - key: MAX_FILE_SIZE_MB
        value: "500"
