const express=require('express');const cookieParser=require('cookie-parser');const multer=require('multer');const {Pool}=require('pg');const {createClient}=require('@supabase/supabase-js');const crypto=require('crypto');
const app=express();app.use(express.json({limit:'2mb'}));app.use(cookieParser());
const PORT=process.env.PORT||10000;const db=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!/localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL)?{rejectUnauthorized:false}:false});
const supa=createClient(process.env.SUPABASE_URL||'',process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||'');
const BUCKETS=['videos','thumbnails','avatars','banners'];const maxMb=Math.max(10,Number(process.env.MAX_FILE_SIZE_MB||100));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:maxMb*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^(video\/(mp4|webm|quicktime)|image\/(jpeg|png|webp))$/i.test(f.mimetype))});
const id=()=>crypto.randomUUID();const identity=req=>req.cookies.lt4_identity||(req.cookies.lt4_identity=id());
async function q(sql,args=[]){return (await db.query(sql,args)).rows}
async function init(){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL не встановлено');if(!process.env.SUPABASE_URL)throw Error('SUPABASE_URL не встановлено');if(!process.env.SUPABASE_SECRET_KEY&&!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Supabase server key не встановлено');await q(`CREATE TABLE IF NOT EXISTS lt4_profiles(id uuid primary key,identity text unique not null,username text not null,bio text default '',avatar_url text default '',created_at timestamptz default now());CREATE TABLE IF NOT EXISTS lt4_channels(id uuid primary key,profile_id uuid unique references lt4_profiles(id) on delete cascade,name text not null,description text default '',avatar_url text default '',banner_url text default '',created_at timestamptz default now());CREATE TABLE IF NOT EXISTS lt4_videos(id uuid primary key,channel_id uuid references lt4_channels(id) on delete cascade,title text not null,description text default '',thumbnail_url text default '',video_url text not null,views bigint default 0,created_at timestamptz default now());CREATE TABLE IF NOT EXISTS lt4_likes(video_id uuid references lt4_videos(id) on delete cascade,identity text not null,primary key(video_id,identity));CREATE TABLE IF NOT EXISTS lt4_subscriptions(channel_id uuid references lt4_channels(id) on delete cascade,identity text not null,primary key(channel_id,identity));CREATE TABLE IF NOT EXISTS lt4_comments(id uuid primary key,video_id uuid references lt4_videos(id) on delete cascade,identity text not null,text text not null,created_at timestamptz default now());CREATE INDEX IF NOT EXISTS lt4_videos_created ON lt4_videos(created_at desc);`);for(const b of BUCKETS){try{await supa.storage.createBucket(b,{public:true})}catch(e){}try{await supa.storage.updateBucket(b,{public:true})}catch(e){}}}
async function store(bucket,file){const path=`${Date.now()}-${crypto.randomUUID()}-${String(file.originalname||'file').replace(/[^a-zA-Z0-9._-]/g,'_')}`;const r=await supa.storage.from(bucket).upload(path,file.buffer,{contentType:file.mimetype,upsert:false});if(r.error)throw r.error;return supa.storage.from(bucket).getPublicUrl(path).data.publicUrl}
app.use((req,res,next)=>{const x=identity(req);if(!req.cookies.lt4_identity)res.cookie('lt4_identity',x,{httpOnly:true,sameSite:'lax',maxAge:31536000000});req.identity=x;next()});
app.get('/api/me',async(req,res)=>{try{const p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0]||null;const c=p?(await q('SELECT * FROM lt4_channels WHERE profile_id=$1',[p.id]))[0]||null:null;res.json({profile:p,channel:c})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/profile',upload.single('avatar'),async(req,res)=>{try{let p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];let avatar=p?.avatar_url||'';if(req.file)avatar=await store('avatars',req.file);if(p){p=(await q('UPDATE lt4_profiles SET username=$1,bio=$2,avatar_url=$3 WHERE id=$4 RETURNING *',[String(req.body.username||'').trim().slice(0,40)||'Глядач',String(req.body.bio||'').slice(0,500),avatar,p.id]))[0]}else p=(await q('INSERT INTO lt4_profiles(id,identity,username,bio,avatar_url) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.identity,String(req.body.username||'').trim().slice(0,40)||'Глядач',String(req.body.bio||'').slice(0,500),avatar]))[0];res.json({profile:p})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/channel',upload.fields([{name:'avatar',maxCount:1},{name:'banner',maxCount:1}]),async(req,res)=>{try{const p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];if(!p)return res.status(400).json({error:'Спочатку створи профіль'});if((await q('SELECT 1 FROM lt4_channels WHERE profile_id=$1',[p.id])).length)return res.status(400).json({error:'Канал уже існує'});const a=req.files?.avatar?.[0]?await store('avatars',req.files.avatar[0]):p.avatar_url||'';const b=req.files?.banner?.[0]?await store('banners',req.files.banner[0]):'';const c=(await q('INSERT INTO lt4_channels(id,profile_id,name,description,avatar_url,banner_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id(),p.id,String(req.body.name||'Мій канал').slice(0,60),String(req.body.description||'').slice(0,1000),a,b]))[0];res.json({channel:c})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/channel',upload.fields([{name:'avatar',maxCount:1},{name:'banner',maxCount:1}]),async(req,res)=>{try{const p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const c=p&&(await q('SELECT * FROM lt4_channels WHERE profile_id=$1',[p.id]))[0];if(!c)return res.status(404).json({error:'Канал не знайдено'});const a=req.files?.avatar?.[0]?await store('avatars',req.files.avatar[0]):c.avatar_url;const b=req.files?.banner?.[0]?await store('banners',req.files.banner[0]):c.banner_url;const x=(await q('UPDATE lt4_channels SET name=$1,description=$2,avatar_url=$3,banner_url=$4 WHERE id=$5 RETURNING *',[String(req.body.name||c.name).slice(0,60),String(req.body.description||'').slice(0,1000),a,b,c.id]))[0];res.json({channel:x})}catch(e){res.status(400).json({error:e.message})}});
async function videoRows(where='',args=[]){return q(`SELECT v.*,c.name channel_name,c.avatar_url channel_avatar,(SELECT count(*) FROM lt4_likes l WHERE l.video_id=v.id)::int likes,(SELECT count(*) FROM lt4_comments cm WHERE cm.video_id=v.id)::int comments,(SELECT count(*) FROM lt4_subscriptions s WHERE s.channel_id=c.id)::int subscribers FROM lt4_videos v JOIN lt4_channels c ON c.id=v.channel_id ${where} ORDER BY v.created_at DESC`,args)}
app.get('/api/home',async(req,res)=>{try{res.json({videos:await videoRows('LIMIT 60')})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/search',async(req,res)=>{try{const s='%'+String(req.query.q||'').trim().slice(0,80)+'%';res.json({videos:await videoRows('WHERE v.title ILIKE $1 OR c.name ILIKE $1 LIMIT 60',[s])})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/channel/:id',async(req,res)=>{try{const c=(await q('SELECT c.*,p.username owner_username FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Канал не знайдено'});const p=(await q('SELECT id FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const sub=(await q('SELECT 1 FROM lt4_subscriptions WHERE channel_id=$1 AND identity=$2',[c.id,req.identity])).length>0;res.json({channel:c,videos:await videoRows('WHERE v.channel_id=$1',[c.id]),subscribed:sub,is_owner:!!(p&&String(p.id)===String(c.profile_id)),subscribers:Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[c.id]))[0].n)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/video/:id',async(req,res)=>{try{const v=(await videoRows('WHERE v.id=$1',[req.params.id]))[0];if(!v)return res.status(404).json({error:'Відео не знайдено'});await q('UPDATE lt4_videos SET views=views+1 WHERE id=$1',[req.params.id]);v.views=Number(v.views)+1;v.liked=!!(await q('SELECT 1 FROM lt4_likes WHERE video_id=$1 AND identity=$2',[v.id,req.identity])).length;v.subscribed=!!(await q('SELECT 1 FROM lt4_subscriptions WHERE channel_id=(SELECT channel_id FROM lt4_videos WHERE id=$1) AND identity=$2',[v.id,req.identity])).length;v.commentsList=await q('SELECT id,text,created_at FROM lt4_comments WHERE video_id=$1 ORDER BY created_at DESC',[v.id]);res.json({video:v})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/subscribe/:channel',async(req,res)=>{try{const x=await q('DELETE FROM lt4_subscriptions WHERE channel_id=$1 AND identity=$2 RETURNING *',[req.params.channel,req.identity]);let subscribed=false;if(!x.length){await q('INSERT INTO lt4_subscriptions(channel_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.channel,req.identity]);subscribed=true}res.json({subscribed,subscribers:Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[req.params.channel]))[0].n)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/like/:video',async(req,res)=>{try{const x=await q('DELETE FROM lt4_likes WHERE video_id=$1 AND identity=$2 RETURNING *',[req.params.video,req.identity]);let liked=false;if(!x.length){await q('INSERT INTO lt4_likes(video_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.video,req.identity]);liked=true}res.json({liked,likes:Number((await q('SELECT count(*) n FROM lt4_likes WHERE video_id=$1',[req.params.video]))[0].n)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/comment/:video',async(req,res)=>{try{const text=String(req.body.text||'').trim().slice(0,1000);if(!text)return res.status(400).json({error:'Напиши коментар'});const c=(await q('INSERT INTO lt4_comments(id,video_id,identity,text) VALUES($1,$2,$3,$4) RETURNING *',[id(),req.params.video,req.identity,text]))[0];res.json({comment:c})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/comment/:id',async(req,res)=>{try{await q('DELETE FROM lt4_comments WHERE id=$1 AND identity=$2',[req.params.id,req.identity]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/upload',upload.fields([{name:'video',maxCount:1},{name:'thumbnail',maxCount:1}]),async(req,res)=>{try{const p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const c=p&&(await q('SELECT * FROM lt4_channels WHERE profile_id=$1',[p.id]))[0];if(!c)return res.status(400).json({error:'Спочатку створи канал'});const f=req.files?.video?.[0];if(!f||!/^video\/(mp4|webm|quicktime)$/i.test(f.mimetype))return res.status(400).json({error:'Додай MP4/WebM/MOV відео'});const vu=await store('videos',f);const tu=req.files?.thumbnail?.[0]?await store('thumbnails',req.files.thumbnail[0]):'';const v=(await q('INSERT INTO lt4_videos(id,channel_id,title,description,thumbnail_url,video_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id(),c.id,String(req.body.title||'Без назви').slice(0,150),String(req.body.description||'').slice(0,5000),tu,vu]))[0];res.json({video:v})}catch(e){res.status(400).json({error:e.message})}});
async function deleteVideo(req,res){try{const p=(await q('SELECT id FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const c=p&&(await q('SELECT id FROM lt4_channels WHERE profile_id=$1',[p.id]))[0];const v=c&&(await q('SELECT * FROM lt4_videos WHERE id=$1 AND channel_id=$2',[req.params.id,c.id]))[0];if(!v)return res.status(403).json({error:'Немає доступу'});await q('DELETE FROM lt4_videos WHERE id=$1',[v.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}}
app.delete('/api/my-video/:id',deleteVideo);
app.delete('/api/my-channel',async(req,res)=>{try{const p=(await q('SELECT id FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const c=p&&(await q('SELECT id FROM lt4_channels WHERE profile_id=$1',[p.id]))[0];if(!c)return res.status(404).json({error:'Канал не знайдено'});await q('DELETE FROM lt4_channels WHERE id=$1',[c.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/owner/login',async(req,res)=>{if(String(req.body.password||'')!==String(process.env.OWNER_PASSWORD||''))return res.status(401).json({error:'Невірний пароль'});res.cookie('lt4_owner','1',{httpOnly:true,sameSite:'lax'});res.json({ok:true})});
app.get('/api/owner/check',(req,res)=>res.json({owner:req.cookies.lt4_owner==='1'}));
app.delete('/api/owner/video/:id',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});await q('DELETE FROM lt4_videos WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.delete('/api/owner/channel/:id',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});await q('DELETE FROM lt4_channels WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.use(express.static(__dirname,{index:'index.html',fallthrough:true}));
init().then(()=>app.listen(PORT,()=>console.log('LimeTube V4 running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
