const express=require('express');
const cookieParser=require('cookie-parser');
const multer=require('multer');
const {Pool}=require('pg');
const crypto=require('crypto');
const app=express();
const PORT=process.env.PORT||10000;
const db=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!/localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL)?{rejectUnauthorized:false}:false});
app.use(express.json({limit:'3mb'}));app.use(cookieParser());
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^(video\/(mp4|webm|quicktime)|image\/(jpeg|png|webp))$/i.test(f.mimetype))});
const mediaUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^(video\/(mp4|webm|quicktime)|image\/(jpeg|png|gif|webp))$/i.test(f.mimetype))});
const id=()=>crypto.randomUUID();const q=async(sql,a=[])=>{const r=await db.query(sql,a);return r.rows};
const ACH=[['bronze','Бронзова',100,'🥉'],['silver','Срібна',5000,'🥈'],['gold','Золота',50000,'🥇'],['diamond','Діамантова',100000,'💎'],['emerald','Емеральдова',350000,'🟩'],['ruby','Рубінова',500000,'♦️'],['netherite','Незеритова',1000000,'⬛'],['creator','Creator',1000000,'👑']];
function ident(req,res){let x=req.get('x-lt4-identity')||req.cookies.lt4_identity;if(!x)x=id();if(req.cookies.lt4_identity!==x)res.cookie('lt4_identity',x,{httpOnly:true,sameSite:'lax',maxAge:31536000000,path:'/'});return x}
app.use((req,res,next)=>{req.identity=ident(req,res);next()});
function img(file,label='Зображення',max=3){if(!file)return '';if(file.size>max*1024*1024)throw Error(`${label}: максимум ${max} МБ`);return `data:${file.mimetype};base64,${file.buffer.toString('base64')}`}
async function init(){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL не встановлено');await q(`
CREATE TABLE IF NOT EXISTS lt4_profiles(id uuid primary key,identity text unique not null,username text not null,bio text default '',avatar_url text default '',coins bigint default 0,last_daily date,profile_frame text default '',avatar_smiley text default '',created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS lt4_channels(id uuid primary key,profile_id uuid unique references lt4_profiles(id) on delete cascade,name text not null,description text default '',avatar_url text default '',banner_url text default '',achievement text default '',theme text default 'lime',verified boolean default false,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS lt4_videos(id uuid primary key,channel_id uuid references lt4_channels(id) on delete cascade,title text not null,description text default '',thumbnail_url text default '',video_url text default '',video_data bytea,video_mime text default 'video/mp4',video_size bigint default 0,views bigint default 0,likes_cache bigint default 0,hashtags text default '',is_short boolean default false,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS lt4_likes(video_id uuid references lt4_videos(id) on delete cascade,identity text not null,primary key(video_id,identity));
CREATE TABLE IF NOT EXISTS lt4_dislikes(video_id uuid references lt4_videos(id) on delete cascade,identity text not null,primary key(video_id,identity));
CREATE TABLE IF NOT EXISTS lt4_subscriptions(channel_id uuid references lt4_channels(id) on delete cascade,identity text not null,created_at timestamptz default now(),primary key(channel_id,identity));
CREATE TABLE IF NOT EXISTS lt4_comments(id uuid primary key,video_id uuid references lt4_videos(id) on delete cascade,identity text not null,text text default '',media_data bytea,media_mime text default '',media_size bigint default 0,parent_id uuid references lt4_comments(id) on delete cascade,pinned boolean default false,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS lt4_comment_likes(comment_id uuid references lt4_comments(id) on delete cascade,identity text not null,primary key(comment_id,identity));
CREATE TABLE IF NOT EXISTS lt4_saved(identity text not null,video_id uuid references lt4_videos(id) on delete cascade,created_at timestamptz default now(),primary key(identity,video_id));
CREATE TABLE IF NOT EXISTS lt4_history(identity text not null,video_id uuid references lt4_videos(id) on delete cascade,watched_at timestamptz default now(),primary key(identity,video_id));
CREATE TABLE IF NOT EXISTS lt4_notifications(id uuid primary key,identity text not null,type text not null,text text not null,video_id uuid references lt4_videos(id) on delete cascade,channel_id uuid references lt4_channels(id) on delete cascade,read boolean default false,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS lt4_live(id uuid primary key,channel_id uuid references lt4_channels(id) on delete cascade,title text not null,status text default 'scheduled',created_at timestamptz default now(),ended_at timestamptz);
CREATE TABLE IF NOT EXISTS lt4_shop_items(id text primary key,name text not null,description text default '',kind text not null,value text not null,price bigint not null default 0);
CREATE TABLE IF NOT EXISTS lt4_inventory(identity text not null,item_id text references lt4_shop_items(id) on delete cascade,created_at timestamptz default now(),primary key(identity,item_id));
ALTER TABLE lt4_profiles ADD COLUMN IF NOT EXISTS coins bigint default 0;ALTER TABLE lt4_profiles ADD COLUMN IF NOT EXISTS last_daily date;ALTER TABLE lt4_profiles ADD COLUMN IF NOT EXISTS profile_frame text default '';ALTER TABLE lt4_profiles ADD COLUMN IF NOT EXISTS avatar_smiley text default '';
ALTER TABLE lt4_channels ADD COLUMN IF NOT EXISTS theme text default 'lime';ALTER TABLE lt4_channels ADD COLUMN IF NOT EXISTS verified boolean default false;
ALTER TABLE lt4_videos ADD COLUMN IF NOT EXISTS hashtags text default '';ALTER TABLE lt4_videos ADD COLUMN IF NOT EXISTS is_short boolean default false;
ALTER TABLE lt4_comments ADD COLUMN IF NOT EXISTS parent_id uuid references lt4_comments(id) on delete cascade;ALTER TABLE lt4_comments ADD COLUMN IF NOT EXISTS pinned boolean default false;
CREATE INDEX IF NOT EXISTS lt4_videos_created ON lt4_videos(created_at desc);CREATE INDEX IF NOT EXISTS lt4_history_time ON lt4_history(watched_at desc);CREATE INDEX IF NOT EXISTS lt4_notifications_time ON lt4_notifications(created_at desc);`);}
async function profile(){return (await q('SELECT * FROM lt4_profiles WHERE identity=$1',[this]))[0]}
async function channelFor(identity){return (await q('SELECT * FROM lt4_channels WHERE profile_id=(SELECT id FROM lt4_profiles WHERE identity=$1)',[identity]))[0]}
async function notify(identity,type,text,video_id=null,channel_id=null){if(!identity)return;await q('INSERT INTO lt4_notifications(id,identity,type,text,video_id,channel_id) VALUES($1,$2,$3,$4,$5,$6)',[id(),identity,type,text,video_id,channel_id]).catch(()=>{})}
async function videoRows(where='',args=[]){return q(`SELECT v.*,c.name channel_name,c.avatar_url channel_avatar,c.verified channel_verified,(SELECT count(*) FROM lt4_likes l WHERE l.video_id=v.id)::int likes,(SELECT count(*) FROM lt4_dislikes d WHERE d.video_id=v.id)::int dislikes,(SELECT count(*) FROM lt4_comments cm WHERE cm.video_id=v.id)::int comments,(SELECT count(*) FROM lt4_subscriptions s WHERE s.channel_id=c.id)::int subscribers FROM lt4_videos v JOIN lt4_channels c ON c.id=v.channel_id ${where} ORDER BY v.created_at DESC`,args)}
app.get('/api/me',async(req,res)=>{try{let p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0]||null;let c=p?(await q('SELECT * FROM lt4_channels WHERE profile_id=$1',[p.id]))[0]||null:null;res.json({profile:p,channel:c})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/profile',upload.single('avatar'),async(req,res)=>{try{let p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const a=req.file?img(req.file,'Аватар'):p?.avatar_url||'';if(p)p=(await q('UPDATE lt4_profiles SET username=$1,bio=$2,avatar_url=$3 WHERE id=$4 RETURNING *',[String(req.body.username||'Глядач').trim().slice(0,40),String(req.body.bio||'').slice(0,500),a,p.id]))[0];else p=(await q('INSERT INTO lt4_profiles(id,identity,username,bio,avatar_url) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.identity,String(req.body.username||'Глядач').trim().slice(0,40),String(req.body.bio||'').slice(0,500),a]))[0];await daily(req.identity);res.json({profile:p})}catch(e){res.status(400).json({error:e.message})}});
async function daily(identity){const p=(await q('SELECT id,last_daily FROM lt4_profiles WHERE identity=$1',[identity]))[0];if(!p)return;const today=new Date().toISOString().slice(0,10);if(String(p.last_daily||'')!==today){await q('UPDATE lt4_profiles SET coins=coins+25,last_daily=$1 WHERE id=$2',[today,p.id]);await notify(identity,'coins','🎁 Щоденний бонус: +25 LimeCoins');}}
app.post('/api/channel',upload.fields([{name:'avatar',maxCount:1},{name:'banner',maxCount:1}]),async(req,res)=>{try{let p=(await q('SELECT * FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];if(!p)p=(await q("INSERT INTO lt4_profiles(id,identity,username) VALUES($1,$2,$3) RETURNING *",[id(),req.identity,'Глядач']))[0];if(await channelFor(req.identity))return res.status(400).json({error:'Канал уже існує'});const a=req.files?.avatar?.[0]?img(req.files.avatar[0],'Аватар'):p.avatar_url||'';const b=req.files?.banner?.[0]?img(req.files.banner[0],'Банер'):'';const c=(await q('INSERT INTO lt4_channels(id,profile_id,name,description,avatar_url,banner_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id(),p.id,String(req.body.name||'Мій канал').slice(0,60),String(req.body.description||'').slice(0,1000),a,b]))[0];res.json({channel:c})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/channel',upload.fields([{name:'avatar',maxCount:1},{name:'banner',maxCount:1}]),async(req,res)=>{try{const c=await channelFor(req.identity);if(!c)return res.status(404).json({error:'Канал не знайдено'});const a=req.files?.avatar?.[0]?img(req.files.avatar[0],'Аватар'):c.avatar_url,b=req.files?.banner?.[0]?img(req.files.banner[0],'Банер'):c.banner_url;const x=(await q('UPDATE lt4_channels SET name=$1,description=$2,avatar_url=$3,banner_url=$4,theme=$5 WHERE id=$6 RETURNING *',[String(req.body.name||c.name).slice(0,60),String(req.body.description||'').slice(0,1000),a,b,String(req.body.theme||c.theme||'lime'),c.id]))[0];res.json({channel:x})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/home',async(req,res)=>{try{res.json({videos:(await videoRows()).slice(0,60),channels:await q('SELECT c.*,(SELECT count(*) FROM lt4_subscriptions s WHERE s.channel_id=c.id)::int subscribers FROM lt4_channels c ORDER BY created_at DESC LIMIT 30')})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/feed',async(req,res)=>{try{res.json({videos:(await videoRows('WHERE v.channel_id IN (SELECT channel_id FROM lt4_subscriptions WHERE identity=$1)',[req.identity])).slice(0,100)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/recommendations',async(req,res)=>{try{const watched=await q('SELECT video_id FROM lt4_history WHERE identity=$1 ORDER BY watched_at DESC LIMIT 20',[req.identity]);const ids=watched.map(x=>x.video_id);let rows=await videoRows(ids.length?'WHERE v.id <> ALL($1::uuid[])':'',ids.length?[ids]:[]);rows.sort((a,b)=>(Number(b.likes)+Number(b.views)/10)-(Number(a.likes)+Number(a.views)/10));res.json({videos:rows.slice(0,40)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/search',async(req,res)=>{try{const term=String(req.query.q||'').trim().slice(0,80);if(!term)return res.json({channels:[],videos:[]});const s='%'+term+'%';const channels=await q(`SELECT c.*,p.username owner_username,(SELECT count(*) FROM lt4_subscriptions ss WHERE ss.channel_id=c.id)::int subscribers,(SELECT count(*) FROM lt4_videos vv WHERE vv.channel_id=c.id)::int video_count FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.name ILIKE $1 OR p.username ILIKE $1 ORDER BY c.name LIMIT 30`,[s]);const videos=await videoRows('WHERE v.title ILIKE $1 OR v.description ILIKE $1 OR v.hashtags ILIKE $1 OR c.name ILIKE $1',[s]);res.json({channels,videos:videos.slice(0,60)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/channel/:id',async(req,res)=>{try{const c=(await q('SELECT c.*,p.username owner_username FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Канал не знайдено'});const p=(await q('SELECT id FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];res.json({channel:c,videos:await videoRows('WHERE v.channel_id=$1',[c.id]),subscribed:!!(await q('SELECT 1 FROM lt4_subscriptions WHERE channel_id=$1 AND identity=$2',[c.id,req.identity])).length,is_owner:!!(p&&String(p.id)===String(c.profile_id)),subscribers:Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[c.id]))[0].n)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/video/:id',async(req,res)=>{try{const v=(await videoRows('WHERE v.id=$1',[req.params.id]))[0];if(!v)return res.status(404).json({error:'Відео не знайдено'});await q('UPDATE lt4_videos SET views=views+1 WHERE id=$1',[v.id]);await q('INSERT INTO lt4_history(identity,video_id,watched_at) VALUES($1,$2,now()) ON CONFLICT(identity,video_id) DO UPDATE SET watched_at=now()',[req.identity,v.id]);await q('DELETE FROM lt4_history WHERE identity=$1 AND video_id IN (SELECT video_id FROM lt4_history WHERE identity=$1 ORDER BY watched_at DESC OFFSET 100)',[req.identity]);await daily(req.identity);v.views=Number(v.views)+1;v.video_url='/media/'+v.id;v.is_owner=!!(await q('SELECT 1 FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.id=$1 AND p.identity=$2',[v.channel_id,req.identity])).length;v.liked=!!(await q('SELECT 1 FROM lt4_likes WHERE video_id=$1 AND identity=$2',[v.id,req.identity])).length;v.disliked=!!(await q('SELECT 1 FROM lt4_dislikes WHERE video_id=$1 AND identity=$2',[v.id,req.identity])).length;v.saved=!!(await q('SELECT 1 FROM lt4_saved WHERE video_id=$1 AND identity=$2',[v.id,req.identity])).length;v.subscribed=!!(await q('SELECT 1 FROM lt4_subscriptions WHERE channel_id=$1 AND identity=$2',[v.channel_id,req.identity])).length;v.commentsList=await q(`SELECT cm.id,cm.text,cm.media_mime,cm.created_at,cm.parent_id,cm.pinned,p.username,p.avatar_url,(cm.identity=$2) is_mine,(SELECT count(*) FROM lt4_comment_likes cl WHERE cl.comment_id=cm.id)::int likes,EXISTS(SELECT 1 FROM lt4_comment_likes cl2 WHERE cl2.comment_id=cm.id AND cl2.identity=$2) liked FROM lt4_comments cm LEFT JOIN lt4_profiles p ON p.identity=cm.identity WHERE cm.video_id=$1 ORDER BY cm.pinned DESC,cm.created_at DESC`,[v.id,req.identity]);v.commentsList=v.commentsList.map(c=>({...c,media_url:c.media_mime?'/comment-media/'+c.id:''}));res.json({video:v})}catch(e){res.status(500).json({error:e.message})}});
app.get('/media/:id',async(req,res)=>{try{const r=await db.query('SELECT video_data,video_mime FROM lt4_videos WHERE id=$1',[req.params.id]);if(!r.rows.length||!r.rows[0].video_data)return res.status(404).end();const data=r.rows[0].video_data,total=data.length;res.setHeader('Content-Type',r.rows[0].video_mime||'video/mp4');res.setHeader('Accept-Ranges','bytes');const range=req.headers.range;if(!range){res.setHeader('Content-Length',total);return res.end(data)}const m=/bytes=(\d*)-(\d*)/.exec(range);if(!m)return res.status(416).end();let s=m[1]?+m[1]:Math.max(total-(+m[2]+1),0),e=m[2]?+m[2]:total-1;if(s>e||s<0||e>=total)return res.status(416).end();res.status(206).set({'Content-Range':`bytes ${s}-${e}/${total}`,'Content-Length':e-s+1});res.end(data.subarray(s,e+1))}catch(e){res.status(500).end()}});
app.get('/comment-media/:id',async(req,res)=>{try{const r=await db.query('SELECT media_data,media_mime FROM lt4_comments WHERE id=$1',[req.params.id]);if(!r.rows.length||!r.rows[0].media_data)return res.status(404).end();res.type(r.rows[0].media_mime||'application/octet-stream').end(r.rows[0].media_data)}catch(e){res.status(500).end()}});
app.post('/api/subscribe/:id',async(req,res)=>{try{const old=await q('DELETE FROM lt4_subscriptions WHERE channel_id=$1 AND identity=$2 RETURNING *',[req.params.id,req.identity]);let on=false;if(!old.length){await q('INSERT INTO lt4_subscriptions(channel_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,req.identity]);on=true;const c=(await q('SELECT profile_id,name FROM lt4_channels WHERE id=$1',[req.params.id]))[0];if(c){const p=(await q('SELECT identity FROM lt4_profiles WHERE id=$1',[c.profile_id]))[0];await notify(p?.identity,'subscriber',`🔔 Новий підписник на канал «${c.name}»`,null,c.id)}}const n=Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[req.params.id]))[0].n);res.json({subscribed:on,subscribers:n})}catch(e){res.status(400).json({error:e.message})}});
async function toggle(table,key,req,res){const old=await q(`DELETE FROM ${table} WHERE video_id=$1 AND identity=$2 RETURNING *`,[req.params.id,req.identity]);let on=false;if(!old.length){await q(`INSERT INTO ${table}(video_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING`,[req.params.id,req.identity]);on=true}res.json({on})}
app.post('/api/like/:id',async(req,res)=>{try{const old=await q('DELETE FROM lt4_likes WHERE video_id=$1 AND identity=$2 RETURNING *',[req.params.id,req.identity]);let liked=false;if(!old.length){await q('INSERT INTO lt4_likes(video_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,req.identity]);liked=true;const v=(await q('SELECT channel_id,title FROM lt4_videos WHERE id=$1',[req.params.id]))[0];if(v){const p=(await q('SELECT p.identity FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.id=$1',[v.channel_id]))[0];if(p?.identity!==req.identity)await notify(p.identity,'like',`💚 Твоє відео «${v.title}» отримало лайк`,v.id,v.channel_id)}}const n=Number((await q('SELECT count(*) n FROM lt4_likes WHERE video_id=$1',[req.params.id]))[0].n);res.json({liked,likes:n})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/dislike/:id',async(req,res)=>{try{await q('DELETE FROM lt4_likes WHERE video_id=$1 AND identity=$2',[req.params.id,req.identity]);const old=await q('DELETE FROM lt4_dislikes WHERE video_id=$1 AND identity=$2 RETURNING *',[req.params.id,req.identity]);let disliked=false;if(!old.length){await q('INSERT INTO lt4_dislikes(video_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,req.identity]);disliked=true}const n=Number((await q('SELECT count(*) n FROM lt4_dislikes WHERE video_id=$1',[req.params.id]))[0].n);res.json({disliked,dislikes:n})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/save/:id',async(req,res)=>{try{const old=await q('DELETE FROM lt4_saved WHERE identity=$1 AND video_id=$2 RETURNING *',[req.identity,req.params.id]);let saved=false;if(!old.length){await q('INSERT INTO lt4_saved(identity,video_id) VALUES($1,$2)',[req.identity,req.params.id]);saved=true}res.json({saved})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/saved',async(req,res)=>{try{res.json({videos:await videoRows('WHERE v.id IN (SELECT video_id FROM lt4_saved WHERE identity=$1)',[req.identity])})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/history',async(req,res)=>{try{res.json({videos:await videoRows('WHERE v.id IN (SELECT video_id FROM lt4_history WHERE identity=$1)',[req.identity])})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/history',async(req,res)=>{await q('DELETE FROM lt4_history WHERE identity=$1',[req.identity]);res.json({ok:true})});
app.post('/api/comment/:video',mediaUpload.single('media'),async(req,res)=>{try{const text=String(req.body.text||'').trim().slice(0,1000),file=req.file,parent=req.body.parent_id||null;if(!text&&!file)return res.status(400).json({error:'Напиши коментар або додай медіа'});const c=(await q('INSERT INTO lt4_comments(id,video_id,identity,text,media_data,media_mime,media_size,parent_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id(),req.params.video,req.identity,text,file?.buffer||null,file?.mimetype||'',file?.size||0,parent]))[0];const v=(await q('SELECT channel_id,title FROM lt4_videos WHERE id=$1',[req.params.video]))[0];if(v){const owner=(await q('SELECT p.identity FROM lt4_channels c JOIN lt4_profiles p ON p.id=c.profile_id WHERE c.id=$1',[v.channel_id]))[0];if(owner?.identity!==req.identity)await notify(owner.identity,'comment',`💬 Новий коментар до «${v.title}»`,v.id,v.channel_id);if(parent){const par=(await q('SELECT identity FROM lt4_comments WHERE id=$1',[parent]))[0];if(par?.identity!==req.identity)await notify(par.identity,'reply','↩️ Хтось відповів на твій коментар',v.id,v.channel_id)}}res.json({comment:c})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/comment-like/:id',async(req,res)=>{try{const old=await q('DELETE FROM lt4_comment_likes WHERE comment_id=$1 AND identity=$2 RETURNING *',[req.params.id,req.identity]);let liked=false;if(!old.length){await q('INSERT INTO lt4_comment_likes(comment_id,identity) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,req.identity]);liked=true}res.json({liked,likes:Number((await q('SELECT count(*) n FROM lt4_comment_likes WHERE comment_id=$1',[req.params.id]))[0].n)})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/comment/:id',async(req,res)=>{await q('DELETE FROM lt4_comments WHERE id=$1 AND identity=$2',[req.params.id,req.identity]);res.json({ok:true})});
app.post('/api/comment-pin/:id',async(req,res)=>{try{const c=(await q('SELECT cm.*,v.channel_id FROM lt4_comments cm JOIN lt4_videos v ON v.id=cm.video_id WHERE cm.id=$1',[req.params.id]))[0];const own=await channelFor(req.identity);if(!c||!own||String(own.id)!==String(c.channel_id))return res.status(403).json({error:'Тільки власник каналу'});await q('UPDATE lt4_comments SET pinned=CASE WHEN id=$1 THEN NOT pinned ELSE false END WHERE video_id=$2',[c.id,c.video_id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/notifications',async(req,res)=>{const n=await q('SELECT * FROM lt4_notifications WHERE identity=$1 ORDER BY created_at DESC LIMIT 100',[req.identity]);res.json({notifications:n})});app.post('/api/notifications/read',async(req,res)=>{await q('UPDATE lt4_notifications SET read=true WHERE identity=$1',[req.identity]);res.json({ok:true})});
app.get('/api/analytics',async(req,res)=>{try{const c=await channelFor(req.identity);if(!c)return res.status(404).json({error:'Канал не знайдено'});const v=await q('SELECT id,title,views,created_at FROM lt4_videos WHERE channel_id=$1 ORDER BY views DESC',[c.id]);const subs=Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[c.id]))[0].n);const likes=Number((await q('SELECT count(*) n FROM lt4_likes l JOIN lt4_videos v ON v.id=l.video_id WHERE v.channel_id=$1',[c.id]))[0].n);res.json({subscribers:subs,totalViews:v.reduce((a,x)=>a+Number(x.views||0),0),likes,videos:v})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/rankings',async(req,res)=>{try{const channels=await q(`SELECT c.id,c.name,c.avatar_url,c.verified,(SELECT count(*) FROM lt4_subscriptions s WHERE s.channel_id=c.id)::int subscribers,(SELECT coalesce(sum(v.views),0) FROM lt4_videos v WHERE v.channel_id=c.id)::bigint views FROM lt4_channels c ORDER BY subscribers DESC,views DESC LIMIT 100`);res.json({channels})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/achievements/:id',async(req,res)=>{const c=(await q('SELECT * FROM lt4_channels WHERE id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Канал не знайдено'});const n=Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[c.id]))[0].n);res.json({subscribers:n,achievements:ACH.map(a=>({id:a[0],name:a[1],threshold:a[2],icon:a[3],unlocked:n>=a[2],equipped:c.achievement===a[0]}))})});
app.post('/api/achievements/:id/equip',async(req,res)=>{const c=await channelFor(req.identity);if(!c||String(c.id)!==String(req.params.id))return res.status(403).json({error:'Тільки власник'});const a=ACH.find(x=>x[0]===req.body.id);const n=Number((await q('SELECT count(*) n FROM lt4_subscriptions WHERE channel_id=$1',[c.id]))[0].n);if(!a||n<a[2])return res.status(400).json({error:'Досягнення не розблоковано'});await q('UPDATE lt4_channels SET achievement=$1 WHERE id=$2',[a[0],c.id]);res.json({ok:true})});
app.post('/api/upload',upload.fields([{name:'video',maxCount:1},{name:'thumbnail',maxCount:1}]),async(req,res)=>{try{const c=await channelFor(req.identity),f=req.files?.video?.[0];if(!c)return res.status(400).json({error:'Спочатку створи канал'});if(!f||!/^video\/(mp4|webm|quicktime)$/i.test(f.mimetype))return res.status(400).json({error:'Додай MP4/WebM/MOV'});const short=String(req.body.is_short||'')==='1';const hashtags=String(req.body.hashtags||'').slice(0,1000);const thumb=req.files?.thumbnail?.[0]?img(req.files.thumbnail[0],'Превʼю'):'';const v=(await q('INSERT INTO lt4_videos(id,channel_id,title,description,thumbnail_url,video_data,video_mime,video_size,hashtags,is_short) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,channel_id,title,description,thumbnail_url,views,created_at,is_short,hashtags',[id(),c.id,String(req.body.title||'Без назви').slice(0,150),String(req.body.description||'').slice(0,5000),thumb,f.buffer,f.mimetype,f.size,hashtags,short]))[0];v.video_url='/media/'+v.id;res.json({video:v})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/shorts',async(req,res)=>{try{res.json({videos:(await videoRows('WHERE v.is_short=true')).slice(0,100)})}catch(e){res.status(500).json({error:e.message})}});
const SHOP=[
{id:'frame_lime',name:'Lime Frame',description:'Неонова рамка навколо аватара.',kind:'frame',value:'lime',price:100},
{id:'frame_gold',name:'Gold Frame',description:'Золота рамка профілю.',kind:'frame',value:'gold',price:300},
{id:'frame_fire',name:'Fire Frame',description:'Вогняна рамка профілю.',kind:'frame',value:'fire',price:500},
{id:'smile_sunglasses',name:'😎 Cool',description:'Смайл біля аватара.',kind:'smiley',value:'😎',price:150},
{id:'smile_crown',name:'👑 Crown',description:'Корона біля аватара.',kind:'smiley',value:'👑',price:350},
{id:'smile_star',name:'⭐ Star',description:'Зірочка біля аватара.',kind:'smiley',value:'⭐',price:200},
{id:'smile_fire',name:'🔥 Fire',description:'Вогник біля аватара.',kind:'smiley',value:'🔥',price:250},
{id:'smile_heart',name:'💚 Lime Heart',description:'Лаймове сердечко біля аватара.',kind:'smiley',value:'💚',price:250}
];
async function seedShop(){for(const x of SHOP)await q('INSERT INTO lt4_shop_items(id,name,description,kind,value,price) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET name=$2,description=$3,kind=$4,value=$5,price=$6',[x.id,x.name,x.description,x.kind,x.value,x.price])}
app.get('/api/shop',async(req,res)=>{try{await seedShop();const p=(await q('SELECT coins,profile_frame,avatar_smiley FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];const owned=await q('SELECT item_id FROM lt4_inventory WHERE identity=$1',[req.identity]);const set=new Set(owned.map(x=>x.item_id));res.json({coins:Number(p?.coins||0),equipped:{frame:p?.profile_frame||'',smiley:p?.avatar_smiley||''},items:(await q('SELECT * FROM lt4_shop_items ORDER BY price,id')).map(x=>({...x,owned:set.has(x.id)}))})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/shop/buy/:id',async(req,res)=>{try{await seedShop();const item=(await q('SELECT * FROM lt4_shop_items WHERE id=$1',[req.params.id]))[0];if(!item)return res.status(404).json({error:'Товар не знайдено'});const p=(await q('SELECT id,coins FROM lt4_profiles WHERE identity=$1 FOR UPDATE',[req.identity]))[0];if(!p)return res.status(400).json({error:'Спочатку створи профіль'});if((await q('SELECT 1 FROM lt4_inventory WHERE identity=$1 AND item_id=$2',[req.identity,item.id])).length)return res.status(400).json({error:'Ти вже маєш цей предмет'});if(Number(p.coins)<Number(item.price))return res.status(400).json({error:'Недостатньо LimeCoins'});await q('UPDATE lt4_profiles SET coins=coins-$1 WHERE id=$2',[item.price,p.id]);await q('INSERT INTO lt4_inventory(identity,item_id) VALUES($1,$2)',[req.identity,item.id]);res.json({ok:true,coins:Number(p.coins)-Number(item.price)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/shop/equip/:id',async(req,res)=>{try{const item=(await q('SELECT * FROM lt4_shop_items WHERE id=$1',[req.params.id]))[0];if(!item)return res.status(404).json({error:'Товар не знайдено'});if(!(await q('SELECT 1 FROM lt4_inventory WHERE identity=$1 AND item_id=$2',[req.identity,item.id])).length)return res.status(403).json({error:'Спочатку купи предмет'});if(item.kind==='frame')await q('UPDATE lt4_profiles SET profile_frame=$1 WHERE identity=$2',[item.value,req.identity]);if(item.kind==='smiley')await q('UPDATE lt4_profiles SET avatar_smiley=$1 WHERE identity=$2',[item.value,req.identity]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/shop/unequip/:kind',async(req,res)=>{try{if(req.params.kind==='frame')await q("UPDATE lt4_profiles SET profile_frame='' WHERE identity=$1",[req.identity]);else if(req.params.kind==='smiley')await q("UPDATE lt4_profiles SET avatar_smiley='' WHERE identity=$1",[req.identity]);else return res.status(400).json({error:'Невідомий тип'});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/coins',async(req,res)=>{const p=(await q('SELECT coins FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];await daily(req.identity);const p2=(await q('SELECT coins FROM lt4_profiles WHERE identity=$1',[req.identity]))[0];res.json({coins:Number(p2?.coins||0)})});
app.post('/api/coins/give',async(req,res)=>{const amount=Math.max(1,Math.min(1000,Number(req.body.amount||0)));const p=await channelFor(req.identity);if(!p||req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});const target=String(req.body.identity||'');await q('UPDATE lt4_profiles SET coins=coins+$1 WHERE identity=$2',[amount,target]);res.json({ok:true})});
app.get('/api/live',async(req,res)=>{const live=await q(`SELECT l.*,c.name channel_name,c.avatar_url FROM lt4_live l JOIN lt4_channels c ON c.id=l.channel_id WHERE l.status='live' ORDER BY l.created_at DESC`);res.json({live})});
app.post('/api/live/start',async(req,res)=>{const c=await channelFor(req.identity);if(!c)return res.status(404).json({error:'Канал не знайдено'});await q("UPDATE lt4_live SET status='ended',ended_at=now() WHERE channel_id=$1 AND status='live'",[c.id]);const x=(await q("INSERT INTO lt4_live(id,channel_id,title,status) VALUES($1,$2,$3,'live') RETURNING *",[id(),c.id,String(req.body.title||'Прямий ефір').slice(0,120)]))[0];res.json({live:x})});
app.post('/api/live/end/:id',async(req,res)=>{const c=await channelFor(req.identity);const x=(await q('SELECT * FROM lt4_live WHERE id=$1',[req.params.id]))[0];if(!c||!x||String(x.channel_id)!==String(c.id))return res.status(403).json({error:'Доступ заборонено'});await q("UPDATE lt4_live SET status='ended',ended_at=now() WHERE id=$1",[x.id]);res.json({ok:true})});
app.get('/api/owner/check',(req,res)=>res.json({owner:req.cookies.lt4_owner==='1'}));app.post('/api/owner/login',(req,res)=>{if(String(req.body.password||'')!==String(process.env.OWNER_PASSWORD||''))return res.status(401).json({error:'Невірний пароль'});res.cookie('lt4_owner','1',{httpOnly:true,sameSite:'lax',maxAge:86400000});res.json({ok:true})});
app.get('/api/owner/data',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});res.json({videos:await videoRows(),channels:await q('SELECT * FROM lt4_channels ORDER BY created_at DESC')})});
app.delete('/api/owner/video/:id',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});await q('DELETE FROM lt4_videos WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.delete('/api/owner/channel/:id',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});await q('DELETE FROM lt4_channels WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.post('/api/owner/verify/:id',async(req,res)=>{if(req.cookies.lt4_owner!=='1')return res.status(403).json({error:'Доступ заборонено'});await q('UPDATE lt4_channels SET verified=NOT verified WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.delete('/api/my-video/:id',async(req,res)=>{const c=await channelFor(req.identity);if(!c)return res.status(404).json({error:'Канал не знайдено'});await q('DELETE FROM lt4_videos WHERE id=$1 AND channel_id=$2',[req.params.id,c.id]);res.json({ok:true})});
app.delete('/api/my-channel',async(req,res)=>{const c=await channelFor(req.identity);if(!c)return res.status(404).json({error:'Канал не знайдено'});await q('DELETE FROM lt4_channels WHERE id=$1',[c.id]);res.json({ok:true})});
app.get('/api/channel/:id/customize',(req,res)=>res.json({ok:true}));
app.use((err,req,res,next)=>{if(err){console.error('LimeTube error:',err);if(req.path.startsWith('/api/'))return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Файл завеликий. Максимум 100 МБ':err.message||'Помилка сервера'});}next(err)});
app.use(express.static(__dirname,{index:'index.html',fallthrough:true}));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('LimeTube V5 running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
